### ISSUE TITLE
[Highlight] Add frequency filter for highlight

### ISSUE THREAD

**Issue by AndyRLP1996** [SFUAnime/Ren#204]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Add a filter to prevent a user from getting spammed with the same highlight in the same channel repeatedly. If a highlight is brought up in conversation, it is easy for a user to get spammed with notifications. When a highlight is detected, have Ren check when the user last received a notification for that highlight and only notify them if the last notification was sent more than X seconds/minutes ago (X is some arbitrary amount of time, perhaps 5 minutes).

**Comment by Injabie3** [comment]
Thanks for the suggestion! 🙏 Just to clarify, since you can have multiple highlight words, are you thinking of having notifications on the basis of:
- Per different trigger word (e.g. if I say word1 in channel A, then it triggers a DM.  I say word2 in channel A within X seconds, then it **will** still trigger a DM).
- Per channel basis (e.g. if I say word1 in channelA, then it triggers a DM.  I say word2 in channel A within X seconds, it **will not** trigger a DM).

**Comment by AndyRLP1996** [comment]
I was thinking ideally both, but per channel would probably be more useful. 
If a highlighted word (say your username) gets mentioned in 2 different chats, you'd probably want notifications for both, whereas if you're going to check a highlight for 1 word anyways, you'll likely see the second one as well.

**Comment by Injabie3** [comment]
I'll refer to X seconds from above as `timeout`.

What are your thoughts on having the `timeout` you mentioned here and in #187 and #205 be the same?  So if you've been DM'd once, you won't receive another DM within `timeout` seconds.  As well, that would mean if you've been active in the last `timeout` seconds in a channel, you won't be DM'd.

**Comment by Injabie3** [comment]
Merged in at f8dd80ed6ad2b18963621e4bb418e5efdb0a16cf
