### ISSUE TITLE
[WordFilter] Track channels by channel ID

### ISSUE THREAD

**Issue by KaguneAstra** [SFUAnime/Ren#232]
Word filter Whitelist doesn't track the channels via ID; when the name of the channel is changed, the white list no longer works

Change the way the cog tracks the whitelisted channels from channel name to ID

Also have to implement a listener for the creation of said whitelisted channel

**Comment by Injabie3** [comment]
I can see some things that we need to handle, of which some you have addressed above:
1. If a channel name is changed to a "whitelisted" one, what should happen?
2. If a new channel is created, do we want to track this change?
3. What happens if a channel name changes from a whitelisted name to one that isn't?
4. How do we remove a channel from the whitelist?  Suppose we have the following case: a new channel is created, which matches a name in the whitelist.  This channel becomes whitelisted.  If we decide the remove this from the whitelist, does it remove the channel name from the whitelist, or the tracked channel ID from the whitelist, or both?

**Comment by KaguneAstra** [comment]
The main solution to these problems is to create a command called "refilter" which will remove the channel ID from the tracked channels list. If a channel is created with a whiltelsited name, it will be tracked and "checkwords" will also run through this list of unfiltered channel ID's before deciding whether to filter or not.

1. The current methods using the names will still function as usual

2. We will only track channels that are created.

3. If the channel is created and tracked by channel ID, it will continue to be unfiltered until refilter is called on that channel/channel ID

4. By using the unfilter command as outlined above

**Comment by Injabie3** [comment]
To come back to this issue, we could also have a listener to see when a channel is changed. Maybe something like:
- If the channel name matches the whitelist, then we can add the ID to it.
- If the channel is removed, we can remove the ID from it.
- If the channel was whitelisted, but the channel name changes, do nothing.

**Comment by Injabie3** [comment]
scrapping idea, closed via c37e2e62e72e1709fa626387e88cc10365b2cdd0 .
