### ISSUE TITLE
Add a timer to renmute

### ISSUE THREAD

**Issue by AndyRLP1996** [SFUAnime/Ren#284]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature
Add a time input to renmute. The mute should expire after the entered amount of time has passed. Should function identically to renpunish.

**Comment by Injabie3** [comment]
`renpunish` is deprecated since this is from the old v2 bot. The v3 bot does have a third party cog that has a similar implementation, but will defer since that also has been [deprecated](https://github.com/flaree/Flare-Cogs/commit/9537a06fffbf99942ad2f4ea7ec19d098114978d#diff-ad148a3ca8bd0ef3b48c52454c493ec5).

Will wait until core Red supports this soon:tm:

**Comment by Injabie3** [comment]
Closing issue as this is now available in Red 3.4.1, see `renmute`
